version: '3'  # Docker Compose file version

services:
  frontend:
    build: ./react-frontend
    ports:
      - '3000:3000'
    networks:
      - my_network

  backend:
    build: ./springboot-backend
    restart: always
    container_name: 'backend'
    ports:
      - '8090:8080'
    depends_on:
      - database
    environment:
      spring.datasource.url: 
    networks:
      - my_network
    links:
      - database

  database:
    image: mysql:5.7
    container_name: 'database'
    environment:
      # MYSQL_HOST: 'database'?
      MYSQL_DATABASE: 'react_crud_db'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password' 
    expose:
      - "3306"
    networks:
      - my_network

networks:
  my_network:
  
